apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homer-route
  namespace: default
spec:
  parentRefs:
  - name: VIP-gateway
    namespace: default
  hostnames:
  - "test.internal"
  rules:
  - backendRefs:
    - name: homer
      port: 80